### ISSUE TITLE
Unhandled exception occured in onAsyncPacket() for mcMMOAction

### ISSUE THREAD

**Issue by RoboMWM** [games647/mcMMOAction#1]
https://gist.github.com/RoboMWM/93aee9fbeb7f2589b3b9

This appears in console whenever an actionbar message is sent from this plugin. I don't see any effects of this error message affecting expected functionality of plugin though.

**Comment by TuxCoding** [comment]
I'll fix it.

**Comment by TuxCoding** [comment]
Sorry for the delay

**Comment by RoboMWM** [comment]
~~Hmm, not sure but it's spamming even more now, even when I say messages now. I'll make sure I actually updated (changing plugin.yml version might help) but either way it's still appearing: https://gist.github.com/RoboMWM/a40413481e2d4d9d8e04~~

Also uploading the .jar should be fine, no need to zip it. Thanks again for the plugin!

~~Update: Updated plugin, still getting errors in console after each chat message in fact.~~

You uploaded an older version of the plugin to releases :/

**Comment by TuxCoding** [comment]
Oh sorry.

**Comment by TuxCoding** [comment]
I uploaded the new version now.

**Comment by TuxCoding** [comment]
> Also uploading the .jar should be fine, no need to zip it. Thanks again for the plugin!

I cannot upload jar versions to Github. Github doesn't accept it.

**Comment by RoboMWM** [comment]
That's odd, I've been able to upload jars to GitHub (see some of my repos like https://github.com/RoboMWM/GP-CustomLogger/releases)

**Comment by TuxCoding** [comment]
In the release section?

**Comment by RoboMWM** [comment]
Yes

**Comment by TuxCoding** [comment]
Oh, you're right. I'm pretty sure it wasn't possible a couple of months ago.

Thank you very much for this hint.

**Comment by RoboMWM** [comment]
Still getting an error with some actions, probably Essentials-related actions (as they occur when Essentials commands are printed such as /apply (I mapped it to an /info chapter) and onJoin for the GeoIP portion) https://gist.github.com/RoboMWM/d289828a2fe4235dd779

It's not printing with most actions though like before so that's better

As before, no visible issues in-game

**Comment by TuxCoding** [comment]
I hope everything works fine now. Sorry for all these issues.
