### ISSUE TITLE
[1.11.2] NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getChatTypes()

### ISSUE THREAD

**Issue by gw2princeps** [games647/mcMMOAction#11]
Hello, 
I'm using latest versions of mcmmo, spigot, protocollib and mcmmoaction. 
https://gist.github.com/SpatiumPrinceps/186ebcc05d16970c89af07f47db73634
Think you compiled against a older version of protocol lib
Greetings!

**Comment by TuxCoding** [comment]
No against 4.3 ProtocolLib. A newer version as yours.

**Comment by gw2princeps** [comment]
Yea, I downloaded an older version of mcmmoactions and its working now. 
The versioning on bukkit dev is a bit weird: you wrote the latest version is compatible with 1.11, but needs 1.12 protocol.

**Comment by TuxCoding** [comment]
No it doesn't. It only requires ProtocolLib 4.13 and ProtocolLib is backwards compatible.
