### ISSUE TITLE
skill progress actionbar

### ISSUE THREAD

**Issue by madtomic** [games647/mcMMOAction#14]
Can you add something like this?

progressmsg: '&a{skillString}: &b{exp}&f/&c{expRemaining} &f| &3Lv: &b{currentLevel}' 

Thanks!

**Comment by TuxCoding** [comment]
You mean the `/<skill>` command?

**Comment by madtomic** [comment]
I'm sorry not being more clear. This is for the message in the actionbar like how your are using it for mcmmoaction.

**Comment by TuxCoding** [comment]
No I meant when do you see this message?

**Comment by madtomic** [comment]
![image](https://user-images.githubusercontent.com/6004542/30592754-0c7b1706-9d16-11e7-8136-cccde2296446.png)

This is what I meant. It updates on the actionbar as player progress the skills.

**Comment by madtomic** [comment]
This is what I want.

**Comment by TuxCoding** [comment]
Although this goes a little bit out of scope of this scope of this project I added it.

**Comment by madtomic** [comment]
Thank you again!
