### ISSUE TITLE
Toggle action bar progress notifications with a command

### ISSUE THREAD

**Issue by whoshenry** [games647/mcMMOAction#17]
My players can't seem to turn the progress bar off. I have given them the the mcMMOAction.command.toggle permission.
Spigot 1.12.2.
mcMMOAction 2.0.1.

**Comment by TuxCoding** [comment]
Should it permanent or could it be temporarily, so that it will be removed after a server restart?

**Comment by whoshenry** [comment]
Ideally if a player has turned it off, they wouldn't want to keep turning it off after every restart.
