### ISSUE TITLE
Cannot cast com.google.gson.JsonPrimitive to com.google.gson.JsonObject

### ISSUE THREAD

**Issue by Spazzinq** [games647/mcMMOAction#18]
https://gist.github.com/Spazzinq/bff95a0d804588090eb93dc8376c3a5e

Version: 2.1.1
TacoSpigot 1.8.8

**Comment by TuxCoding** [comment]
Could you test it before I release it please?

https://github.com/games647/mcMMOAction/releases/tag/2.1.2

**Comment by Spazzinq** [comment]
It's fixed! Sorry, I just back home :)
