### ISSUE TITLE
Permission check spam.

### ISSUE THREAD

**Issue by mibby** [games647/mcMMOAction#19]
mcMMOAction v2.0

Permission checks seem to constantly be spammed with McMMOAction. Turning on permission check verbose, this is spammed constantly.

```
[21:33:19] [main/INFO]: [CHAT] [LP] VB > mibby - mcmmoaction.display - true
```
http://paste.ubuntu.com/25757291/

I didn't have any mcmmo action bar up. I was just standing still when monitoring permission checks. Perhaps it could be optimized a bit?

**Comment by TuxCoding** [comment]
>Turning on permission check verbose, this is spammed constantly.

That's what verbose means. If you activate that in LuckPerms, it will display this message every time a plugin performs a permissions check. mcMMOAction checks this permission for every message the user receives.

**Comment by mibby** [comment]
Right, I understand. However I had no mcMMOAction bar. I was simply standing still with nothing going on. Turning on verbose to debug another permission issue, mcmmoAction was spamming that permission check repeatedly while nothing was going on.

**Comment by TuxCoding** [comment]
Do you checked if you actually have this permission and if you have all required dependencies installed.

**Comment by mibby** [comment]
Yes. McMMOAction functions as intended normally and the permission is granted to everyone by default in the plugin.yml.

I'm grouped an admin position with a ```*``` wildcard for inheritance, but that shouldn't affect anything. McMMOAction just seems to spam checks on me.

**Comment by TuxCoding** [comment]
>McMMOAction just seems to spam checks on me.

As I said this message is normal and a feature of LuckPerms to notify the user when the plugin checks the permission.

**Comment by mibby** [comment]
Yes, I know the verbose output is normal. What isn't normal is mcMMOAction spamming permission checks on me when nothing is going on, repeatedly non-stop dozens of times a second. This has to affect performance in a negative way.

**Comment by TuxCoding** [comment]
It checks the permission before it tries to read the message. That's nothing you have to worry about.

**Comment by mibby** [comment]
It should _only_ check the permission when there is an mcmmo message to be read. So it can convert the message into an actionbar notification if the user has permission. Not spam checks for the sake of it when nothing is going on.

**Comment by TuxCoding** [comment]
It just checks the permission and then checks if it's a mcMMO message. If something of that is false it just ignores the packet. Then the chat packet will continue as normal completely unmodified. As I said that's nothing to worry about.

**Comment by mibby** [comment]
Maybe you aren't understanding? 

You should _not_ check permissions constantly for the sake of trying to catch a message. You are forcing permission lookups 183 times a second! This is terrible for performance and in poor hindsight. As well as makes LuckPerms verbose impossible to read and stop since it constantly spams. You should hook into mcmmo to display messages as actionbars instead of the normal messages and only do a permission check to see if a user has permission for that message when the event comes through, to display it as an actionbar.

This is with just McMMO, McMMOAction, ProtocolLib, and LuckPerms installed. Standing still, not doing anything, only me online.
```
[02:36:03] [main/INFO]: [CHAT] [LP] VB > mibby - mcmmoaction.display - true
...
```

**Comment by TuxCoding** [comment]
>This is terrible for performance and in poor hindsight

I don't really think so, because it's only a small check with already cached values (like a hashset) of the permissions plugin. If I'm wrong send me a timings report and I will change it.

>You should hook into mcmmo to display messages as actionbars instead of messages

That requires a Java Proxy before the sendMessage call which is even worse for performance and increases the complexity a lot..

> lookups 183 times a second! 

It depends on the message you receive. It just checks it when you receive a new message. 

To actual check if it's a mcMMO message, I have to convert the json into legacy chat and back. If you think it's really better to make this check before checking the permission, then I will change it, but I don't think there will be much a difference.

**Comment by mibby** [comment]
> It just checks it when you receive a new message.

No it doesn't. It checks the permission constantly, no messages are occurring.

**Comment by TuxCoding** [comment]
Show me in the source-code where you see the permission check other than that:

On receiving chat packet for each player:
https://github.com/games647/mcMMOAction/blob/d97afc45c140f4a0b9cab545cbaf1c61f15ef0a0/src/main/java/com/github/games647/mcmmoaction/listener/MessageListener.java#L65

**Comment by mibby** [comment]
That is the only place in your source-code where you check for the permission, but it is occurring hundreds of times a second. If I understand correctly, you are reading the chat position (readChatPosition) regardless of whether there is chat incoming. So you are just constantly checking chat and the permission for no reason.

**Comment by TuxCoding** [comment]
>If I understand correctly, you are reading the chat position (readChatPosition) regardless of whether there is chat incoming

That's a chat packet event and is only fired if a chat packet is sent, but for each player. Maybe your server sends empty chat packets?

**Comment by mibby** [comment]
> is only fired if a chat packet is sent.

Well I guess apparently it isn't.

**Comment by TuxCoding** [comment]
I checked it and it is like I said. It only fires the event if there is a chat message of any kind for that player. Tested with:
- ColorConsole
- EssentialsX
- LagMonitor
- mcMMO
- ProtocolLib
- mcMMOAction

Test code on line 60
```java
        System.out.println("ON CHAT PACKET for " + packetEvent.getPlayer());
```

**Comment by mibby** [comment]
Here is a test server so you can test it yourself.
https://www.dropbox.com/s/0j28udrj6ch4cjl/test.zip?dl=0

```/lp user <yourname> parent set Admin``` - from console
```/lp verbose on``` - from in-game

You'll notice when it spams, you can't even turn verbose off with ```/lp verbose off```.

McMMO v1.5.09-SNAPSHOT dev 208 (as of commit https://github.com/mcMMO-Dev/mcMMO/commit/eb4960f307cbcafb513cd34430655c5d406c14ec)
McMMOAction v2.1.2 (compiled as of commit https://github.com/games647/mcMMOAction/commit/d97afc45c140f4a0b9cab545cbaf1c61f15ef0a0)
Paper dev 1241 (Spigot 1.12.2)
ProtocolLib 4.4.0-SNAPSHOT dev 390

**Comment by TuxCoding** [comment]
That's it, you should not invoke the verbose command from ingame. It will loop forever. 

Print message for check -> mcMMOAction check permission -> Print message for check -> ...

**Comment by mibby** [comment]
Oh, I guess that makes sense as to why it happens then.

In that case, wouldn't it be better to only check for mcmmo messages so plugin functionality of LuckPerms can still be used and so the permission is only checked on messages from mcmmo rather than all chat output? Chat can be quite active with a large community online.

**Comment by TuxCoding** [comment]
>Chat can be quite active with a large community online.

I don't think it makes any performance difference, but I changed it for LuckPerms.
