### ISSUE TITLE
Extreme error on login that kicks

### ISSUE THREAD

**Issue by RainOfPain125** [games647/mcMMOAction#21]
This plugin in combination with another plugin (chat item) unloads a big error into console everytime someone tries to join, and it kicks them

https://pastebin.com/HJ22Au7x

No idea why, no idea how. I'm just gonna uninstall the plugin for now.

**Comment by TuxCoding** [comment]
Please post your server, ProtocolLib and mcMMOAction version.

**Comment by RainOfPain125** [comment]
mc.royalarms.net
ProtocolLib version 4.4.0-SNAPSHOT-b390
Sadly I uninstalled it, but I took it out, and it's 2.3.2

Oddly, people with OP do not get kicked.

**Comment by TuxCoding** [comment]
Please post the exact server version too.

**Comment by TuxCoding** [comment]
I found out that ezProtector sends invalid packets. It only sends a chat message without it position. I'll fix it to let mcMMOAction fail silently. That's also the issue that mcMMOAction is not the only plugin that prints this error.
