### ISSUE TITLE
Total placeholder

### ISSUE THREAD

**Issue by Sikatsu** [games647/mcMMOAction#24]
Hi,

I'd like to request a total placeholder so I can show current xp/total xp instead of current xp/remaining xp.

**Comment by TuxCoding** [comment]
You mean the total experience points for the next level?

**Comment by Sikatsu** [comment]
Yes!

**Comment by Sikatsu** [comment]
Will this be released on spigot anytime soon or are there any devbuilds?

**Comment by TuxCoding** [comment]
Dev builds are automatically created once I push changes here.

**Comment by Sikatsu** [comment]
I updated to the devbuild and the progress action bar is no longer working?
