### ISSUE TITLE
McMMO Action - Not displaying in Action Bar

### ISSUE THREAD

**Issue by iSkeptical** [games647/mcMMOAction#27]
**Startup Log & Shutdown / Restart Log**
https://pastebin.com/WmywJ6Zk
Throwns an error on restart/shutdown but not on startup.

**Images of Issue:** 
https://imgur.com/Jsm4n82
As you can see it displays all actions in the chat after it said in action bar,
https://imgur.com/i1uobTn
Toggled it again and it still displays everything in chat.

**Plugins:**
CoreProtect, PermissionsEX, Pex-Chat, ColoredSigns, mcMMO, ProtocolLib, mcMMOAction

**mcMMO version:**
https://popicraft.net/jenkins/job/mcMMO/ 
Build #54
McMMO Action v2.3.2

**Server Version** [My host hasn't updated the jar in awhile and does not support custom jars]:
Craftbukkit version git-Spigot-947a8e7-17ff1e0 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Hope this is what you wanted from me instead of leaving a review on spigot forums. Thank you.

**Comment by iSkeptical** [comment]
However, when I tested this off my host, it worked with 0 issues. I'm contacting my host now. Maybe its loading action first before the dependencies?

**Comment by iSkeptical** [comment]
I found the solution to my own problem. 

I'm using minecraft-hosting.pro. 
Updating the jar manually and renaming it to any version you see on their list and selecting Java 8 (Legacy) will fix this issue. 

No idea why though.

**Comment by TuxCoding** [comment]
I tried to make some changes which should fix it. I'm re-opening if it's still broken.
