### ISSUE TITLE
Plugin crashes on start up

### ISSUE THREAD

**Issue by Sti-jn** [games647/mcMMOAction#29]
When starting up the server the plugin crashes on the latest mcMMO version (happened with quite a few builds before this as well)

https://pastebin.com/CDheM1vR

**Comment by TuxCoding** [comment]
Please download a dev build of mcMMOAction as well.

**Comment by Sti-jn** [comment]
Sorry I never realized there was a dev build for mcMMOAction (which is dumb of me not to check properly) It should be installed tomorrow so unless that still doesn't work I'll close this issue
