### ISSUE TITLE
Chat messages out of order when sent in bulk

### ISSUE THREAD

**Issue by ezeiger92** [games647/mcMMOAction#3]
When a plugin sends many lines of text, it is often received out of order. The packet adapter is async, so it's not that surprising, but it is incredibly annoying (borderline breaking) for many of our plugins.

**Comment by TuxCoding** [comment]
@ezeiger92 But everything should be handled in just **one** worker thread. Do you use other chat packet manipulating plugins?

**Comment by ezeiger92** [comment]
You are right, I should have tested that before posting.

If used with MineverseChat or PlacholderAPI+PlaceholderInjector, messages get scrambled. However, when those three plugins are used together without this one, messages are fine.

**Comment by TuxCoding** [comment]
> If used with MineverseChat

I could only find VentureChat. Is it the same?

**Comment by ezeiger92** [comment]
Yea, they changed the name -_-

**Comment by TuxCoding** [comment]
You're right. I could reproduce this issue with these plugins and once I changed it to a sync listener the issue was gone.

**Comment by TuxCoding** [comment]
I changed it to sync listener until I find a solution to fix it.

**Comment by ezeiger92** [comment]
Cool, I'll give it a shot in a couple hours. Thanks!
