### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by slvlr** [games647/mcMMOAction#32]
Hi, Will this plugin be updated to work with 1.14.2 please?

**Comment by TuxCoding** [comment]
This shouldn't be necessary, because it already is compatible. Do you have any errors?

**Comment by slvlr** [comment]
Previously this wasn't working, and was displaying messages in chat. It is now working... 
The only warning I have is this now but I don't think is an issue. 

[19:08:41] [Server thread/WARN]: Plugin mcMMOAction v2.3.2 does not specify an api-version.
