### ISSUE TITLE
Not working for herbalism notifications

### ISSUE THREAD

**Issue by jakkuh** [games647/mcMMOAction#34]
This is on mcMMO classic, on 1.12.2 paper.

As you can see in the image below, Herbalism luck notifications don't seem to work with the action bar plugin.

https://i.imgur.com/D7ukCVY.png

**Comment by TuxCoding** [comment]
The image is behind login wall.

**Comment by jakkuh** [comment]
New image link: https://i.imgur.com/D7ukCVY.png
