### ISSUE TITLE
mcmmo dependency

### ISSUE THREAD

**Issue by RoboMWM** [games647/mcMMOAction#4]
Hi, more of a question than an issue... how are you able to build this plugin without specifying any source for the mcMMO jar file? I'd figure you'd have to at least set a system path or a maven repo for it...?

**Comment by TuxCoding** [comment]
You're right. It's just cached in my local repository. You can find the old versions of mcMMO [here](http://repo.md-5.net/content/groups/public) and the new versions [here](https://github.com/mcMMO-Dev/mcMMO/blob/master/pom.xml#L158).
